# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "void"

paginate:         5

# URL
baseurl:            "http://angelsimon.github.io"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

tags: "linux" "raspberry pi" "reviews" "videojuegos" "90s" "hardware" "software" "programación" "código fuente" "nes" "pc" "dos" "mis proyectos"

# Navigation
nav:
  - name:           "About"
    href:           "about"
  - name:						"Categorías"
    href:						"categories"
  - name:           "Tags"
    href:           "tags"
#  - name:           "Download"
#    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
